# Generated by Django 5.1.3 on 2024-12-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image_path', models.CharField(help_text='图片在static目录下的相对路径，例如: images/crops/玉米.jpg', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PestDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_path', models.CharField(help_text='图片在static目录下的相对路径，例如: images/pests/病虫害.jpg', max_length=255)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_diseases', to='index.crop')),
            ],
        ),
    ]


